overrides:
  form-data: 4.0.6

allowBuilds:
  '@parcel/watcher': set this to true or false
  contentful: set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
  vue-demi: set this to true or false
